version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - .:/var/www/reane-backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=reane-db.ctmy8geo4ay7.ap-northeast-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=reane
      - DB_USERNAME={DB_USERNAME}
      - DB_PASSWORD={DB_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: reane-db.ctmy8geo4ay7.ap-northeast-1.rds.amazonaws.com
      PMA_PORT: 3306
      PMA_USER: {DB_USERNAME}
      PMA_PASSWORD: {DB_PASSWORD}
    ports:
      - 8081:80
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  mysql-volume: