version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./src:/var/www
  mysql:
    image: mysql:8.3
    container_name: mysql_db
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: reana
      MYSQL_ROOT_PASSWORD: ga255430
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
    ports:
      - 8081:80
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  mysql-volume:
