<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActionSeeder extends Seeder
{
    public function run()
    {
        $reach_hanahana = DB::table('reaches')->where('name', '体重65kg以下の達成')->first();
        $skills_hanahana = DB::table('skills')->where('reach_id', $reach_hanahana->id)->get();

        $reach_ohtani = DB::table('reaches')->where('name', 'ドラフト１位８球団から指名される')->first();
        $skills_ohtani = DB::table('skills')->where('reach_id', $reach_ohtani->id)->get();

        $reach_frontend = DB::table('reaches')->where('name', 'フロントエンドエンジニアを目指す')->first();
        $skills_frontend = DB::table('skills')->where('reach_id', $reach_frontend->id)->get();

        $reach_backend = DB::table('reaches')->where('name', 'バックエンドエンジニアを目指す')->first();
        $skills_backend = DB::table('skills')->where('reach_id', $reach_backend->id)->get();

        $reach_takken = DB::table('reaches')->where('name', '宅建を取得する')->first();
        $skills_takken = DB::table('skills')->where('reach_id', $reach_takken->id)->get();

        $reach_kigyo = DB::table('reaches')->where('name', '起業する')->first();
        $skills_kigyo = DB::table('skills')->where('reach_id', $reach_kigyo->id)->get();

        $actions = [
            // 食事管理に関連するアクション
            ['name' => 'カロリー制限食事計画', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[0]->id],
            ['name' => '定期的な食事記録', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[0]->id],
            ['name' => '野菜中心の食事', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[0]->id],
            ['name' => '糖分摂取制限', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[0]->id],
            ['name' => 'プロテイン摂取', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[0]->id],
            ['name' => '食事バランスチェック', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[0]->id],
            ['name' => '週一回の断食', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[0]->id],
            ['name' => '水分補給の計画', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[0]->id],
            // 運動に関連するアクション
            ['name' => '毎朝のジョギング', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[1]->id],
            ['name' => '週三回の筋トレ', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[1]->id],
            ['name' => 'ヨガセッション', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[1]->id],
            ['name' => 'ストレッチ', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[1]->id],
            ['name' => 'サイクリング', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[1]->id],
            ['name' => 'スイミング', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[1]->id],
            ['name' => 'ウォーキング', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[1]->id],
            ['name' => 'エアロビクス', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[1]->id],
            // 睡眠に関連するアクション
            ['name' => '早寝早起き', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[2]->id],
            ['name' => '睡眠時間の記録', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[2]->id],
            ['name' => '寝室の環境整備', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[2]->id],
            ['name' => 'リラクゼーション', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[2]->id],
            ['name' => 'カフェイン摂取の制限', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[2]->id],
            ['name' => '昼寝の計画', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[2]->id],
            ['name' => '夜の電子機器使用制限', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[2]->id],
            ['name' => '睡眠アプリの使用', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[2]->id],
            // ストレス管理に関連するアクション
            ['name' => '瞑想', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[3]->id],
            ['name' => '深呼吸法', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[3]->id],
            ['name' => 'リラックス音楽の視聴', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[3]->id],
            ['name' => '趣味の時間', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[3]->id],
            ['name' => '自然散策', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[3]->id],
            ['name' => 'ジャーナリング', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[3]->id],
            ['name' => 'ストレス解消運動', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[3]->id],
            ['name' => '笑いの時間', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[3]->id],
            // 水分補給に関連するアクション
            ['name' => '1日2リットルの水摂取', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[4]->id],
            ['name' => '飲み物の記録', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[4]->id],
            ['name' => '水分補給のリマインダー設定', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[4]->id],
            ['name' => 'スポーツドリンクの摂取', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[4]->id],
            ['name' => '水筒の持ち歩き', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[4]->id],
            ['name' => 'カフェイン摂取制限', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[4]->id],
            ['name' => 'アルコール摂取制限', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[4]->id],
            ['name' => '水の味を楽しむ', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[4]->id],
            // 健康診断に関連するアクション
            ['name' => '定期健康診断の予約', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[5]->id],
            ['name' => '健康診断結果の分析', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[5]->id],
            ['name' => '血液検査', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[5]->id],
            ['name' => '視力検査', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[5]->id],
            ['name' => '聴力検査', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[5]->id],
            ['name' => '内科検診', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[5]->id],
            ['name' => '歯科検診', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[5]->id],
            ['name' => '体力測定', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[5]->id],
            // 休息に関連するアクション
            ['name' => '定期的な休憩', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[6]->id],
            ['name' => 'リラックス方法の実践', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[6]->id],
            ['name' => '休日の計画', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[6]->id],
            ['name' => '趣味の時間', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[6]->id],
            ['name' => 'マッサージ', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[6]->id],
            ['name' => '音楽鑑賞', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[6]->id],
            ['name' => '映画鑑賞', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[6]->id],
            ['name' => '温泉旅行', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[6]->id],
            // メンタルケアに関連するアクション
            ['name' => '自己反省', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[7]->id],
            ['name' => 'カウンセリング', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[7]->id],
            ['name' => 'メンタルヘルスのチェック', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[7]->id],
            ['name' => 'ポジティブ思考', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[7]->id],
            ['name' => 'リラクゼーション', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[7]->id],
            ['name' => '心の健康管理', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[7]->id],
            ['name' => '感情日記', 'is_completed' => true, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[7]->id],
            ['name' => 'ストレス緩和策', 'is_completed' => false, 'reach_id' => $reach_hanahana->id, 'skill_id' => $skills_hanahana[7]->id],

            //大谷チャート
            // キレ
            ['name' => 'リストの強化', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[0]->id],
            ['name' => '下半身手動', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[0]->id],
            ['name' => '可動域', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[0]->id],
            ['name' => '回転数アップ', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[0]->id],
            ['name' => 'ボールを前でリリース', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[0]->id],
            ['name' => '力まない', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[0]->id],
            ['name' => '角度をつける', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[0]->id],
            ['name' => '上からボールをたたく', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[0]->id],
            // スピード160kg/h
            ['name' => '体重増加', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[1]->id],
            ['name' => '肩周りの強化', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[1]->id],
            ['name' => 'ピッチングを増やす', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[1]->id],
            ['name' => 'ライナーキャッチボール', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[1]->id],
            ['name' => '可動域', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[1]->id],
            ['name' => '体幹強化', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[1]->id],
            ['name' => '軸でまわる', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[1]->id],
            ['name' => '下肢の強化', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[1]->id],
            // 変化球
            ['name' => 'スライダーのキレ', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[2]->id],
            ['name' => '左打者への決め球', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[2]->id],
            ['name' => '奥行きをイメージ', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[2]->id],
            ['name' => 'ストライクからボールに', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[2]->id],
            ['name' => 'ストレートと同じフォームで投げる', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[2]->id],
            ['name' => '遅く落差のあるカーブ', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[2]->id],
            ['name' => 'カウントボールを増やす', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[2]->id],
            ['name' => 'フォークの完成', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[2]->id],
            // 運
            ['name' => '部屋掃除', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[3]->id],
            ['name' => '審判さんへの態度', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[3]->id],
            ['name' => '本を読む', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[3]->id],
            ['name' => '応援される人間になる', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[3]->id],
            ['name' => 'プラス思考', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[3]->id],
            ['name' => '道具を大切に', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[3]->id],
            ['name' => 'ゴミ拾い', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[3]->id],
            ['name' => 'あいさつ', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[3]->id],
            // 人間性
            ['name' => '計画性', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[4]->id],
            ['name' => '感謝', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[4]->id],
            ['name' => '継続力', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[4]->id],
            ['name' => '信頼される人間', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[4]->id],
            ['name' => '礼儀', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[4]->id],
            ['name' => '思いやり', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[4]->id],
            ['name' => '感性', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[4]->id],
            ['name' => '愛される人間', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[4]->id],
            // メンタル
            ['name' => '頭は冷静に心は熱く', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[5]->id],
            ['name' => '雰囲気に流されない', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[5]->id],
            ['name' => '袴を思いやる心', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[5]->id],
            ['name' => '勝利への執念', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[5]->id],
            ['name' => '波をつくらない', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[5]->id],
            ['name' => 'ピンチに強い', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[5]->id],
            ['name' => 'はっきりと目的・目標をもつ', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[5]->id],
            ['name' => '一喜一憂しない', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[5]->id],
            // 体つくり
            ['name' => 'F5Q90KG', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[6]->id],
            ['name' => 'RSQ130kg', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[6]->id],
            ['name' => '食事夜７杯朝３杯', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[6]->id],
            ['name' => '可動域', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[6]->id],
            ['name' => 'スタミナ', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[6]->id],
            ['name' => '柔軟性', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[6]->id],
            ['name' => '体のケア', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[6]->id],
            ['name' => 'サプリメントを飲む', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[6]->id],
            // コントロール
            ['name' => '軸をぶらさない', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[7]->id],
            ['name' => '不安をなくす', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[7]->id],
            ['name' => 'メンタルコントロールする', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[7]->id],
            ['name' => '体を開かない', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[7]->id],
            ['name' => '下肢の強化', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[7]->id],
            ['name' => 'リリースポイントの安定', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[7]->id],
            ['name' => 'インステップ改善', 'is_completed' => true, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[7]->id],
            ['name' => '体幹強化', 'is_completed' => false, 'reach_id' => $reach_ohtani->id, 'skill_id' => $skills_ohtani[7]->id],

            // frontend
            // HTML
            ['name' => 'HTML5の基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[0]->id],
            ['name' => 'CSSグリッドを使ってレイアウトを作成', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[0]->id],
            ['name' => 'レスポンシブデザインを実践', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[0]->id],
            ['name' => 'Flexboxをマスターする', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[0]->id],
            ['name' => 'CSSプリプロセッサを学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[0]->id],
            ['name' => 'HTML/CSSのベストプラクティスを学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[0]->id],
            ['name' => 'BEM記法を学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[0]->id],
            ['name' => 'CSSアニメーションを学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[0]->id],
            // JavaScriptに関連するアクション
            ['name' => 'JavaScriptの基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[1]->id],
            ['name' => 'ES6の新機能を理解する', 'is_completed' => true, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[1]->id],
            ['name' => '非同期処理を学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[1]->id],
            ['name' => 'DOM操作を理解する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[1]->id],
            ['name' => 'イベントハンドリングを学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[1]->id],
            ['name' => 'JavaScriptライブラリを使用する', 'is_completed' => true, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[1]->id],
            ['name' => 'デバッグ技術を学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[1]->id],
            ['name' => 'JavaScriptでプロジェクトを作成', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[1]->id],
            // React.jsに関連するアクション
            ['name' => 'Reactの基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[2]->id],
            ['name' => 'Reactコンポーネントを作成', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[2]->id],
            ['name' => '状態管理を理解する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[2]->id],
            ['name' => 'React Routerを使用する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[2]->id],
            ['name' => 'Reduxを学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[2]->id],
            ['name' => 'React Hooksを学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[2]->id],
            ['name' => 'Context APIを理解する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[2]->id],
            ['name' => 'Reactでプロジェクトを作成', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[2]->id],
            // TypeScriptに関連するアクション
            ['name' => 'TypeScriptの基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[3]->id],
            ['name' => 'TypeScriptで型定義を理解する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[3]->id],
            ['name' => 'TypeScriptとJavaScriptの違いを理解する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[3]->id],
            ['name' => 'TypeScriptでクラスを作成', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[3]->id],
            ['name' => 'TypeScriptでインターフェースを学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[3]->id],
            ['name' => 'TypeScriptでジェネリクスを理解する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[3]->id],
            ['name' => 'TypeScriptでデコレーターを学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[3]->id],
            ['name' => 'TypeScriptでプロジェクトを作成', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[3]->id],
            // デザインに関連するアクション
            ['name' => '基本的なデザイン原則を学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[4]->id],
            ['name' => 'カラースキームを理解する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[4]->id],
            ['name' => 'タイポグラフィを学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[4]->id],
            ['name' => 'デザインツールを使用する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[4]->id],
            ['name' => 'レスポンシブデザインを学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[4]->id],
            ['name' => 'ユーザーエクスペリエンスを理解する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[4]->id],
            ['name' => 'プロトタイピングを学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[4]->id],
            ['name' => 'デザインシステムを構築', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[4]->id],
            // アクセシビリティに関連するアクション
            ['name' => 'アクセシビリティの基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[5]->id],
            ['name' => 'スクリーンリーダーの使用を理解する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[5]->id],
            ['name' => 'ARIA属性を学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[5]->id],
            ['name' => 'キーボードナビゲーションを実装する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[5]->id],
            ['name' => '色のコントラストをチェックする', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[5]->id],
            ['name' => '音声入力の対応を理解する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[5]->id],
            ['name' => 'アクセシビリティのテストを実施する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[5]->id],
            ['name' => 'アクセシビリティレポートを作成', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[5]->id],
            // パフォーマンス最適化に関連するアクション
            ['name' => 'Webパフォーマンスの基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[6]->id],
            ['name' => '画像の最適化を実行する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[6]->id],
            ['name' => 'コード分割を実施する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[6]->id],
            ['name' => 'キャッシュ戦略を学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[6]->id],
            ['name' => 'Lazy Loadingを実装する', 'is_completed' => true, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[6]->id],
            ['name' => 'ネットワークリクエストを最適化する', 'is_completed' => true, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[6]->id],
            ['name' => 'メモリリークを防止する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[6]->id],
            ['name' => 'パフォーマンスモニタリングツールを使用する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[6]->id],
            // テストに関連するアクション
            ['name' => 'ユニットテストを学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[7]->id],
            ['name' => 'エンドツーエンドテストを実施する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[7]->id],
            ['name' => 'テスト駆動開発を理解する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[7]->id],
            ['name' => 'テストフレームワークを学ぶ', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[7]->id],
            ['name' => 'テストカバレッジを確認する', 'is_completed' => true, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[7]->id],
            ['name' => 'モックを使用する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[7]->id],
            ['name' => '継続的インテグレーションを学ぶ', 'is_completed' => true, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[7]->id],
            ['name' => '自動テストを設定する', 'is_completed' => false, 'reach_id' => $reach_frontend->id, 'skill_id' => $skills_frontend[7]->id],

            // backend

            ['name' => 'SQLの基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[0]->id],
            ['name' => 'データベース設計を理解する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[0]->id],
            ['name' => 'インデックスの使い方を学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[0]->id],
            ['name' => 'トランザクション管理を学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[0]->id],
            ['name' => 'リレーショナルデータベースを理解する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[0]->id],
            ['name' => 'NoSQLデータベースを学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[0]->id],
            ['name' => 'バックアップとリカバリを学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[0]->id],
            ['name' => 'データベースのパフォーマンスチューニングを行う', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[0]->id],
            // API開発に関連するアクション
            ['name' => 'RESTful APIの基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[1]->id],
            ['name' => 'GraphQLを理解する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[1]->id],
            ['name' => 'APIドキュメントを作成する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[1]->id],
            ['name' => '認証と認可を実装する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[1]->id],
            ['name' => 'APIゲートウェイを学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[1]->id],
            ['name' => 'APIのバージョン管理を行う', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[1]->id],
            ['name' => 'APIのパフォーマンスを最適化する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[1]->id],
            ['name' => 'APIテストを実施する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[1]->id],
            // サーバー管理に関連するアクション
            ['name' => 'Linuxの基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[2]->id],
            ['name' => 'サーバーの設定を行う', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[2]->id],
            ['name' => 'Webサーバーを設定する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[2]->id],
            ['name' => 'ネットワーク設定を理解する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[2]->id],
            ['name' => 'SSL証明書を導入する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[2]->id],
            ['name' => 'サーバーのモニタリングを行う', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[2]->id],
            ['name' => 'サーバーのセキュリティを強化する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[2]->id],
            ['name' => 'サーバーログの管理を行う', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[2]->id],
            // セキュリティに関連するアクション
            ['name' => 'セキュリティの基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[3]->id],
            ['name' => '脆弱性のスキャンを実施する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[3]->id],
            ['name' => 'CSRF対策を実装する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[3]->id],
            ['name' => 'XSS対策を実装する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[3]->id],
            ['name' => 'SQLインジェクション対策を実装する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[3]->id],
            ['name' => 'セキュアコーディングを学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[3]->id],
            ['name' => 'セキュリティ監査を実施する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[3]->id],
            ['name' => 'セキュリティポリシーを策定する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[3]->id], // テストとデバッグに関連するアクション
            ['name' => 'ユニットテストを学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[4]->id],
            ['name' => 'インテグレーションテストを実施する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[4]->id],
            ['name' => 'エンドツーエンドテストを学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[4]->id],
            ['name' => 'デバッグ技術を向上させる', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[4]->id],
            ['name' => 'テスト駆動開発を理解する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[4]->id],
            ['name' => '継続的テストを実施する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[4]->id],
            ['name' => 'テストフレームワークを学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[4]->id],
            ['name' => 'コードカバレッジを向上させる', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[4]->id],
            // パフォーマンス最適化に関連するアクション
            ['name' => 'パフォーマンスの基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[5]->id],
            ['name' => 'プロファイリングツールを使用する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[5]->id],
            ['name' => 'コードの最適化を行う', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[5]->id],
            ['name' => 'クエリの最適化を学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[5]->id],
            ['name' => 'キャッシュを利用する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[5]->id],
            ['name' => 'ロードバランシングを実装する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[5]->id],
            ['name' => 'コンテンツデリバリネットワークを利用する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[5]->id],
            ['name' => 'パフォーマンスモニタリングを行う', 'is_completed' => true, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[5]->id],
            // クラウドサービスに関連するアクション
            ['name' => 'AWSの基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[6]->id],
            ['name' => 'GCPの基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[6]->id],
            ['name' => 'Azureの基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[6]->id],
            ['name' => 'クラウドストレージを利用する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[6]->id],
            ['name' => 'クラウドコンピューティングを学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[6]->id],
            ['name' => 'サーバーレスアーキテクチャを理解する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[6]->id],
            ['name' => 'クラウドサービスのセキュリティを学ぶ', 'is_completed' => true, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[6]->id],
            ['name' => 'クラウドネイティブアプリケーションを開発する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[6]->id],
            // CI/CDに関連するアクション
            ['name' => '継続的インテグレーションを学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[7]->id],
            ['name' => '継続的デリバリーを実装する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[7]->id],
            ['name' => '自動デプロイメントを設定する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[7]->id],
            ['name' => 'CI/CDツールを学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[7]->id],
            ['name' => 'パイプラインの最適化を行う', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[7]->id],
            ['name' => 'デプロイメントストラテジーを理解する', 'is_completed' => true, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[7]->id],
            ['name' => 'CI/CDのベストプラクティスを学ぶ', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[7]->id],
            ['name' => 'CI/CDをプロジェクトに導入する', 'is_completed' => false, 'reach_id' => $reach_backend->id, 'skill_id' => $skills_backend[7]->id],

            // 宅建
            // 法令上の制限に関連するアクション
            ['name' => '都市計画法を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[0]->id],
            ['name' => '建築基準法を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[0]->id],
            ['name' => '農地法の基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[0]->id],
            ['name' => '自然公園法を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[0]->id],
            ['name' => '土地区画整理法を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[0]->id],
            ['name' => '宅地造成等規制法を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[0]->id],
            ['name' => '道路法の基本を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[0]->id],
            ['name' => '景観法を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[0]->id],
            // 宅地建物取引業法に関連するアクション
            ['name' => '宅地建物取引業法の基礎を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[1]->id],
            ['name' => '重要事項説明書の作成を練習する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[1]->id],
            ['name' => '契約書の作成方法を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[1]->id],
            ['name' => '宅建業者の義務を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[1]->id],
            ['name' => '取引態様の表示方法を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[1]->id],
            ['name' => '報酬規定を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[1]->id],
            ['name' => '監督処分について学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[1]->id],
            ['name' => '免許の申請手続きを理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[1]->id],
            // 民法に関連するアクション
            ['name' => '契約法の基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[2]->id],
            ['name' => '債権法を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[2]->id],
            ['name' => '物権法を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[2]->id],
            ['name' => '親族法を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[2]->id],
            ['name' => '相続法を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[2]->id],
            ['name' => '不法行為法を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[2]->id],
            ['name' => '民法改正点を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[2]->id],
            ['name' => '裁判例を調べる', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[2]->id],
            // 税法に関連するアクション
            ['name' => '所得税法の基本を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[3]->id],
            ['name' => '法人税法を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[3]->id],
            ['name' => '消費税法を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[3]->id],
            ['name' => '不動産取得税を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[3]->id],
            ['name' => '登録免許税を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[3]->id],
            ['name' => '固定資産税を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[3]->id],
            ['name' => '印紙税を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[3]->id],
            ['name' => '相続税法を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[3]->id],
            // 建築基準法に関連するアクション
            ['name' => '建築確認申請を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[4]->id],
            ['name' => '用途地域を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[4]->id],
            ['name' => '建ぺい率と容積率を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[4]->id],
            ['name' => '建築物の高さ制限を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[4]->id],
            ['name' => '防火地域・準防火地域を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[4]->id],
            ['name' => '日影規制を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[4]->id],
            ['name' => '建築設備の基準を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[4]->id],
            ['name' => '耐震基準を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[4]->id],
            // 土地・建物に関連するアクション
            ['name' => '土地の評価方法を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[5]->id],
            ['name' => '建物の評価方法を理解する', 'is_completed' => true, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[5]->id],
            ['name' => '不動産鑑定士の業務を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[5]->id],
            ['name' => '土地の取引価格を調査する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[5]->id],
            ['name' => '建物の取引価格を調査する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[5]->id],
            ['name' => '不動産取引の流れを学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[5]->id],
            ['name' => '宅地建物取引士の役割を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[5]->id],
            ['name' => '土地・建物に関する法令を学ぶ', 'is_completed' => true, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[5]->id],
            // 宅建業者の役割に関連するアクション
            ['name' => '宅建業者の業務内容を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[6]->id],
            ['name' => '宅建業者の法的責任を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[6]->id],
            ['name' => '宅建業者の報酬規定を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[6]->id],
            ['name' => '宅建業者の営業活動を理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[6]->id],
            ['name' => '宅建業者の顧客対応を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[6]->id],
            ['name' => '宅建業者の契約書作成を学ぶ', 'is_completed' => true, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[6]->id],
            ['name' => '宅建業者のトラブル対応を学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[6]->id],
            ['name' => '宅建業者の業務フローを理解する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[6]->id],
            // 実務経験に関連するアクション
            ['name' => '実務研修に参加する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[7]->id],
            ['name' => '先輩宅建士の仕事を見学する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[7]->id],
            ['name' => '実務に関する書籍を読む', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[7]->id],
            ['name' => '実務経験を積む', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[7]->id],
            ['name' => '実務に関するセミナーに参加する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[7]->id],
            ['name' => '実務に関するケーススタディを学ぶ', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[7]->id],
            ['name' => '実務経験を振り返る', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[7]->id],
            ['name' => '実務に関する疑問を解決する', 'is_completed' => false, 'reach_id' => $reach_takken->id, 'skill_id' => $skills_takken[7]->id],


            // 起業する
            ['name' => '市場のニーズを調査する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[0]->id],
            ['name' => '競合分析を行う', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[0]->id],
            ['name' => 'ユニークな価値提案を考える', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[0]->id],
            ['name' => '顧客の課題を特定する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[0]->id],
            ['name' => 'アイデアのプロトタイプを作成する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[0]->id],
            ['name' => 'フィードバックを収集する', 'is_completed' => true, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[0]->id],
            ['name' => 'アイデアを改良する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[0]->id],
            ['name' => '市場への参入戦略を考える', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[0]->id],
            // マーケットリサーチに関連するアクション
            ['name' => '市場規模を調査する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[1]->id],
            ['name' => 'ターゲット顧客を特定する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[1]->id],
            ['name' => '市場トレンドを分析する', 'is_completed' => true, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[1]->id],
            ['name' => '競合企業をリサーチする', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[1]->id],
            ['name' => '顧客インタビューを実施する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[1]->id],
            ['name' => 'アンケート調査を実施する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[1]->id],
            ['name' => 'データを分析する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[1]->id],
            ['name' => '市場調査レポートを作成する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[1]->id],
            // ビジネスプラン作成に関連するアクション
            ['name' => 'ビジネスプランの概要を作成する', 'is_completed' => true, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[2]->id],
            ['name' => 'ミッションとビジョンを明確にする', 'is_completed' => true, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[2]->id],
            ['name' => 'マーケティング戦略を策定する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[2]->id],
            ['name' => '財務計画を作成する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[2]->id],
            ['name' => '組織構造を設計する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[2]->id],
            ['name' => 'リスク管理計画を立てる', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[2]->id],
            ['name' => 'ビジネスモデルを定義する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[2]->id],
            ['name' => '実行計画を作成する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[2]->id],
            // 資金調達に関連するアクション
            ['name' => '資金調達方法を調査する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[3]->id],
            ['name' => '投資家をリサーチする', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[3]->id],
            ['name' => 'ビジネスピッチを作成する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[3]->id],
            ['name' => '投資家とのミーティングを設定する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[3]->id],
            ['name' => 'クラウドファンディングを計画する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[3]->id],
            ['name' => '融資申請を準備する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[3]->id],
            ['name' => '財務予測を作成する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[3]->id],
            ['name' => '資金調達計画を実行する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[3]->id],
            // 法律・規制に関連するアクション
            ['name' => '企業設立手続きを調査する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[4]->id],
            ['name' => '事業許可を取得する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[4]->id],
            ['name' => '商標登録を行う', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[4]->id],
            ['name' => '契約書を作成する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[4]->id],
            ['name' => '労働法を理解する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[4]->id],
            ['name' => '税法を理解する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[4]->id],
            ['name' => 'プライバシー法を学ぶ', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[4]->id],
            ['name' => '法的リスクを管理する', 'is_completed' => true, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[4]->id],
            // マーケティングに関連するアクション
            ['name' => 'マーケティング戦略を立てる', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[5]->id],
            ['name' => 'ソーシャルメディアマーケティングを学ぶ', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[5]->id],
            ['name' => 'コンテンツマーケティングを実践する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[5]->id],
            ['name' => 'SEO対策を行う', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[5]->id],
            ['name' => 'メールマーケティングを学ぶ', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[5]->id],
            ['name' => '広告キャンペーンを計画する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[5]->id],
            ['name' => 'マーケティング分析を実施する', 'is_completed' => true, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[5]->id],
            ['name' => 'ブランド戦略を構築する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[5]->id],
            // チームビルディングに関連するアクション
            ['name' => 'チームの目標を設定する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[6]->id],
            ['name' => '効果的なリーダーシップを学ぶ', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[6]->id],
            ['name' => 'チームメンバーを採用する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[6]->id],
            ['name' => 'チームのコミュニケーションを向上させる', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[6]->id],
            ['name' => 'チームビルディング活動を実施する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[6]->id],
            ['name' => 'チームのパフォーマンスを評価する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[6]->id],
            ['name' => 'チームメンバーの成長をサポートする', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[6]->id],
            ['name' => 'チームの目標達成を支援する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[6]->id],
            // 経営管理に関連するアクション
            ['name' => '財務管理を学ぶ', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[7]->id],
            ['name' => '事業運営計画を立てる', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[7]->id],
            ['name' => '業務プロセスを最適化する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[7]->id],
            ['name' => 'リスク管理計画を実施する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[7]->id],
            ['name' => '顧客関係管理を強化する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[7]->id],
            ['name' => '事業継続計画を立てる', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[7]->id],
            ['name' => '経営戦略を策定する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[7]->id],
            ['name' => '事業のパフォーマンスを監視する', 'is_completed' => false, 'reach_id' => $reach_kigyo->id, 'skill_id' => $skills_kigyo[7]->id],
        ];
        DB::table('actions')->insert($actions);
    }
}
